# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAppCommodity',
            fields=[
                ('material', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name=b'Material')),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=b'Change')),
            ],
        ),
        migrations.CreateModel(
            name='CostAppCost',
            fields=[
                ('product_code', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name=b'Product Code')),
                ('product_name', models.CharField(max_length=255, verbose_name=b'Product Name')),
                ('product_type', models.CharField(max_length=45, verbose_name=b'Product Type')),
                ('standard_minutes', models.IntegerField(default=0, verbose_name=b'Standard Minutes')),
                ('wastage_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=b'Wastage Allowance')),
                ('overhead', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=b'Overhead ($)')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CostAppCommodity')),
            ],
        ),
        migrations.CreateModel(
            name='CostAppDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin', models.CharField(max_length=45, verbose_name=b'Country of Origin')),
                ('country_of_destination', models.CharField(max_length=255, verbose_name=b'Country of Destination')),
                ('material', models.CharField(max_length=45, verbose_name=b'Material')),
                ('duty_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=b'Duty Rate')),
                ('transportation', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=b'Transportation')),
            ],
        ),
        migrations.CreateModel(
            name='CostAppVendor',
            fields=[
                ('vendor_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name=b'Vendor Name')),
                ('country_of_origin', models.CharField(max_length=45, verbose_name=b'Country of Origin')),
                ('efficiency_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=b'Efficiency Adjustment')),
            ],
        ),
        migrations.CreateModel(
            name='CostAppWage',
            fields=[
                ('country_of_origin', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name=b'Country of Origin')),
                ('wage_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=b'Wage Rate ($/hour)')),
            ],
        ),
        migrations.DeleteModel(
            name='Wage',
        ),
        migrations.RenameField(
            model_name='productmaster',
            old_name='vedor_code',
            new_name='vendor_code',
        ),
    ]
