# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170123_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdata',
            name='moq_multiple',
            field=models.FloatField(default=0, verbose_name=b'MOQ Multiple'),
        ),
    ]
