# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170123_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costappcommodity',
            name='change',
            field=models.FloatField(default=0, verbose_name=b'Change'),
        ),
        migrations.AlterField(
            model_name='costappcost',
            name='overhead',
            field=models.FloatField(default=0, verbose_name=b'Overhead ($)'),
        ),
        migrations.AlterField(
            model_name='costappcost',
            name='wastage_allowance',
            field=models.FloatField(default=0, verbose_name=b'Wastage Allowance'),
        ),
        migrations.AlterField(
            model_name='costappduty',
            name='duty_rate',
            field=models.FloatField(default=0, verbose_name=b'Duty Rate'),
        ),
        migrations.AlterField(
            model_name='costappduty',
            name='transportation',
            field=models.FloatField(default=0, verbose_name=b'Transportation'),
        ),
        migrations.AlterField(
            model_name='costappvendor',
            name='efficiency_adjustment',
            field=models.FloatField(default=0, verbose_name=b'Efficiency Adjustment'),
        ),
        migrations.AlterField(
            model_name='costappwage',
            name='wage_rate',
            field=models.FloatField(default=0, verbose_name=b'Wage Rate ($/hour)'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='fixed_cost_percentage',
            field=models.FloatField(default=0, verbose_name=b'Fixed Cost %'),
        ),
        migrations.AlterField(
            model_name='shipmentdata',
            name='fob',
            field=models.FloatField(default=0, verbose_name=b'FoB'),
        ),
        migrations.AlterField(
            model_name='shipmentdata',
            name='order_quantity',
            field=models.FloatField(default=0, verbose_name=b'Order Quantity'),
        ),
        migrations.AlterField(
            model_name='shipmentdata',
            name='shipment_value',
            field=models.FloatField(default=0, verbose_name=b'Shipment Value'),
        ),
        migrations.AlterField(
            model_name='shipmentdata',
            name='shipment_value_sku_order',
            field=models.FloatField(default=0, verbose_name=b'Shipment Value SKU Order'),
        ),
    ]
