# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170123_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_office', models.CharField(max_length=45, verbose_name=b'Buying Office')),
                ('category', models.CharField(max_length=255, verbose_name=b'Category')),
                ('vendor_name', models.CharField(max_length=255, verbose_name=b'Vendor Name')),
                ('fin_month', models.DateTimeField(default=0, verbose_name=b'FinMonth')),
                ('year', models.IntegerField(default=0, verbose_name=b'Year')),
                ('sum_shipment_value', models.FloatField(default=0, verbose_name=b'Shipment Value')),
                ('sum_order_quantity', models.FloatField(default=0, verbose_name=b'Order Quantity')),
                ('avg_fob', models.FloatField(default=0, verbose_name=b'Average FoB')),
                ('avg_shipment_value_sku', models.FloatField(default=0, verbose_name=b'Average Shipment Value per SKU')),
                ('avg_order_quantity_sku', models.FloatField(default=0, verbose_name=b'Average Order Quantity per SKU')),
                ('avg_shipment_value_po', models.FloatField(default=0, verbose_name=b'Average Shipment Value per PO')),
                ('avg_order_quantity_po', models.FloatField(default=0, verbose_name=b'Average Order Quantity per PO')),
                ('num_sku', models.IntegerField(default=0, verbose_name=b'Number of Distinct SKU')),
                ('num_po', models.IntegerField(default=0, verbose_name=b'Number of Distinct PO')),
                ('shipment_growth', models.FloatField(default=0, verbose_name=b'Shipment Growth (%)')),
                ('growth_factor', models.FloatField(default=0, verbose_name=b'Growth Factor (%)')),
                ('MOT', models.FloatField(default=0, verbose_name=b'Money On the Table')),
            ],
        ),
    ]
