# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shipmentcalc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinces_with_factories', models.CharField(max_length=255, verbose_name=b'Provinces with Factories')),
                ('pct_total_workers_for_vietnam', models.FloatField(default=0, verbose_name=b'Percent Total Workers for Vietnam')),
                ('min_wage_2015', models.FloatField(default=0, verbose_name=b'2015 Min Wage')),
                ('min_wage_2016', models.FloatField(default=0, verbose_name=b'2016 Min Wage')),
                ('total_premium', models.FloatField(default=0, verbose_name=b'Total Premium')),
                ('total_wage_LLC', models.FloatField(default=0, verbose_name=b'Total Wage (LLC)')),
                ('total_wage_USD', models.FloatField(default=0, verbose_name=b'Total Wage (USD)')),
            ],
        ),
    ]
