# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_laborrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceLocationCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_office', models.CharField(max_length=45, verbose_name=b'Buying Office')),
                ('vendor_name', models.CharField(max_length=255, verbose_name=b'Vendor Name')),
                ('vendor_code', models.CharField(max_length=45, verbose_name=b'Vendor Code')),
                ('product_country_of_origin', models.CharField(max_length=45, verbose_name=b'Country of Origin')),
            ],
        ),
        migrations.AddField(
            model_name='shipmentcalc',
            name='vendor_code',
            field=models.CharField(default=b'', max_length=45, verbose_name=b'Vendor Code'),
        ),
    ]
