# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170131_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentcalc',
            name='MOT',
        ),
        migrations.AddField(
            model_name='shipmentcalc',
            name='TSP_ValueGrowth',
            field=models.FloatField(default=0, verbose_name=b'Theoretical Saving Potential - Value Growth'),
        ),
    ]
