# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170131_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentcalc',
            name='fixed_cost_percentage',
            field=models.FloatField(default=0, verbose_name=b'Fixed Cost %'),
        ),
    ]
