# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shipmentcalc_fixed_cost_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentcalc',
            name='avg_shipment_value_sku_order',
            field=models.FloatField(default=0, verbose_name=b'Shipment Value SKU Order'),
        ),
        migrations.AddField(
            model_name='shipmentcalc',
            name='avg_vendor_moq',
            field=models.IntegerField(default=0, verbose_name=b'Vendor MOQ'),
        ),
        migrations.AddField(
            model_name='shipmentcalc',
            name='moq_category',
            field=models.CharField(default=b'', max_length=45, verbose_name=b'MOQ Category'),
        ),
        migrations.AddField(
            model_name='shipmentcalc',
            name='moq_category_index',
            field=models.IntegerField(default=0, verbose_name=b'MOQ Category Index'),
        ),
        migrations.AddField(
            model_name='shipmentcalc',
            name='moq_multiple',
            field=models.FloatField(default=0, verbose_name=b'MOQ Multiple'),
        ),
        migrations.AddField(
            model_name='shipmentcalc',
            name='sum_shipment_value_sku_order',
            field=models.FloatField(default=0, verbose_name=b'Shipment Value SKU Order'),
        ),
        migrations.AddField(
            model_name='shipmentcalc',
            name='sum_vendor_moq',
            field=models.IntegerField(default=0, verbose_name=b'Vendor MOQ'),
        ),
    ]
