# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170206_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentcalc',
            name='avg_shipment_value_sku_order',
        ),
        migrations.RemoveField(
            model_name='shipmentcalc',
            name='avg_vendor_moq',
        ),
    ]
