# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170206_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
                ('Rate', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=13)),
                ('Days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyYearly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
                ('Rate', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='GDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
                ('Rate', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='LaborOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('Provinces', models.CharField(max_length=30)),
                ('Percentage', models.DecimalField(decimal_places=10, max_digits=13)),
                ('MinWage2015', models.DecimalField(decimal_places=2, max_digits=13)),
                ('MinWage2016', models.DecimalField(decimal_places=2, max_digits=13)),
                ('Premium', models.DecimalField(decimal_places=10, max_digits=13)),
                ('WageLLC', models.DecimalField(decimal_places=2, max_digits=13)),
                ('WageUSD', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
                ('Rate', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
    ]
