# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cpi_currencymonthly_currencyyearly_gdp_laboroverview_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentcalc',
            name='sum_shipment_value_prior',
            field=models.FloatField(default=0, verbose_name=b'Prior Year Shipment Value'),
        ),
    ]
