# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_shipmentcalc_sum_shipment_value_prior'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentcalc',
            name='TSP_MOQ',
            field=models.FloatField(default=0, verbose_name=b'Theoretical Saving Potential - MOQ'),
        ),
    ]
