# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170215_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentcalc',
            old_name='TSP_CostRecovery',
            new_name='TSP_CostPriceRecovery',
        ),
        migrations.AddField(
            model_name='shipmentcalc',
            name='avg_cost_price',
            field=models.FloatField(default=0, verbose_name=b'Average cost price'),
        ),
    ]
