# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170215_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentcalc',
            name='avg_cost_price_prior',
            field=models.FloatField(default=0, verbose_name=b'Prior Average cost price'),
        ),
    ]
