# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_shipmentcalc_avg_cost_price_prior'),
    ]

    operations = [
        migrations.AddField(
            model_name='moqcategory',
            name='moq_savings',
            field=models.FloatField(default=0, verbose_name=b'MOQ Efficiency Savings'),
        ),
    ]
