# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_costappcomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='costappcost',
            name='material_cost',
            field=models.FloatField(default=0, verbose_name=b'Raw Material Cost'),
        ),
    ]
