# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_costappcost_material_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyyearly',
            name='Rate',
            field=models.DecimalField(decimal_places=5, max_digits=13),
        ),
    ]
